export const FEATURES_ENDPOINTS = {
  getOrganisations: '/usm-administration/rest/organisations',
  getSubscriptionsList: '/subscription/rest/subscription/list',
  getOrganisationDetails: '/usm-administration/rest/organisations/',
  createSubscription: '/subscription/rest/subscription',
  editSubscription: '/subscription/rest/subscription/',
  getSubscriptionDetails: '/subscription/rest/subscription/',
  checkSubscriptionName: '/subscription/rest/subscription/available',
  getSystemAreaLayers: '/spatial/rest/area/layers',
  getBasicMapConfig: '/spatial/rest/config/basic',
  getUserAreaLayers: '/spatial/rest/userarea/layers',
  getSystemAreasByFilter: '/spatial/rest/area/byfilter',
  getUserAreasByFilter: '/spatial/rest/userarea/byfilter',
  getAreaProperties: '/spatial/rest/area/properties',
  getAreaDetails: '/spatial/rest/area/details',
  getAssets: '/asset/rest/asset/zeroBased/list',
  getAssetsGroups: '/asset/rest/group/zeroBased/list?user=',
  getAssetsGroupsDetails: '/asset/rest/group/',
  deleteSubscription: '/subscription/rest/subscription/',
  getActivitiesMasterData: '/mdr/rest/cl/search',
  createManualSubscription: '/subscription/rest/subscription/create-manual',
  fetchAllSenders: '/user/rest/organisations/withEndPointsAndChannels',
  fetchDefaultEmailBody: '/subscription/rest/email/defaultBodyTemplate'
};
